import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App'; 

const text = `... synaptical composability ... *:= all operations ... 
  ... meaningful communication ... simple formatting ... best synonyms ...
  ... this language developed for ... bots. humans. ai. ...
  ... '*' := bold convection operator ...
  ... ''' := constructor ...
  ... '.' := object.class.recursion (asc) ...
  ... '( or )' := encapsulation ...
  ... '--' := subordinate
  ... license. mymadness ... credits. ai.bots.search_engines.chat.community`; // Replace with your actual text

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <App text={text} /> 
);
